spring.application.name=service
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/oauth2/jwks
//spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082
logging.level.org.springframework.security=DEBUG