spring.application.name=service
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090